# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Fahmi Syaifudin
title: Senior Backend Engineer
email: fahmi@ekan.id

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: fahf74xx
github_username: fahmisyaifudin
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: syaifudin.fahmi
linkedin_username: fahmisyaifudin
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
#   - title: itsgoingto.be
#     icon: fas fa-globe
#     url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Fahmi Syaifudin  have experience to develop and plan a software project especially web platform, manage Linux server and cloud service. I also have capability to manage small team. Beside of that work activity, I am also active in IT community for updating my skills, because technology growth massively

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Ekan Indonesia
        sub_title: Product Engineer 3 - Backend
        caption: November 2022 - Present
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          eKan is a company that provides traceable, trustworthy, and sustainable seafood traders in Indonesia, my job are :
          - Design and Develop API using Typescript and Fastify
          - Using Nx monorepo that holds the source code for multiple applications and libraries
          - Create pipeline for build, test, deploy using Gitlab CI
          - Implementing infrastructure as code for the managing and provisioning of infrastructure using Terraform with Google Cloud Platform provider

      - layout: left
        title: Telkomsel
        sub_title: IT Operation
        caption: Desember 2020 - November 2022
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          Working as contract employee, and placed in IT Operation Regional Jatim Telkomsel, my job are :
          - Rewrite internal attendance system with Nuxt JS
          - Develop API for Grapari device checklist mobile apps
          - Monitor and Operate ETL process to get site performance data (Traffic, Payload, Revenue, VLR)
          - Set the server environment to pass security vulnerability assessment
          - Initiate using internal Git Server and Jenkins CI/CD tools
          - Deploy web service or database service and manage them using Docker

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Institut Teknologi Sepuluh Nopember (ITS)
        caption: 2023 - Present
        sub_title: Master degree of Information Systems
        description: | # this will include new lines to allow paragraphs
          Experience :
          - Web Development Curriculum Team Google Developer Student Club (GDSCS) ITS
      - layout: left
        title: Institut Teknologi Adhitama Surabaya (ITATS)
        caption: 2020 - 2022
        sub_title: Bachelor degree of Informatics Engineering
        description: | # this will include new lines to allow paragraphs
          Achievement:
          - Best Paper 1 Seminar Implementasi Teknologi Informasi dan Komunikasi

      - layout: left
        title: Politeknik Elektronika Negeri Surabaya
        caption: 2016 - 2019
        sub_title: Associate degree of Telecommuncation Engineering
        description: | # this will include new lines to allow paragraphs
          Experience :
          - Head of Entrepreneurship Department at Hima Telkom 2018-2019
          - Entrepreneurship Staff at Hima Telkom 2017-2018
          Achievement :
          - Representative of PENS in Indonesian Student Business Competition Ristekdikti (KBMI) 2019
          - Passed Funding for the Entrepreneurial Student Program (PMW) 2018

  # - title: A Little More About Me
  #   layout: text
  #   content: | # this will include new lines to allow paragraphs
  #     Alongside my interests in networks and software engineering some of my other interests and hobbies are:
  #     - Rock climbing
  #     - Gaming
  #     - Knitting
  #     - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

  #     Look at this cool image
  #     ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
